//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCreda.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int UserId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> PointsEarned { get; set; }
        public Nullable<int> DoctorPoints { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
    }
}
