//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCreda.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public int SpecialtyId { get; set; }
        public string SpecialtyName { get; set; }
    }
}
